apiRules:
  - exclude:
      uidRegex: ^Callvote\.Properties
      type: Namespace

  - exclude:
      uidRegex: ^Callvote\.Commands
      type: Namespace

  - exclude:
      uidRegex: ^Callvote\.Configuration
      type: Namespace
