name: Release DLL and Nuget Package
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore Packages
        run: nuget restore Callvote.sln
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Download references
        run: Invoke-WebRequest -Uri "https://exmod-team.github.io/SL-References/Dev.zip"
          -OutFile "References.zip"
      - name: Extract Refs
        run: |
          mkdir Callvote\lib
          tar -xf References.zip -C Callvote/lib
      - name: Build EXILED
        run: msbuild Callvote.sln -p:Configuration=EXILED -p:Platform=x64
      - name: Build LabAPI
        run: msbuild Callvote.sln -p:Configuration=Release -p:Platform=x64
      - name: Create Release with Dlls
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          generate_release_notes: true
          files: |
            Callvote/bin/x64/EXILED/net48/Callvote-EXILED.dll
            Callvote/bin/x64/Release/net48/Callvote-LabAPI.dll
      - name: Publish to NuGet.org
        run: dotnet nuget push Callvote/bin/x64/Release/*.nupkg --api-key ${{ secrets.NUGET_API }} --source https://api.nuget.org/v3/index.json
      - name: Publish to GitHub Packages
        run: dotnet nuget push Callvote/bin/x64/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
